# Generated by Django 3.1 on 2020-09-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrun',
            name='happens',
        ),
        migrations.AddField(
            model_name='eventrun',
            name='date',
            field=models.DateField(default='2023-10-27'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventrun',
            name='time',
            field=models.TimeField(default='23:30:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('FN', 'fun'), ('RX', 'relax'), ('EX', 'experience'), ('SI', 'sights')], default='FN', max_length=20),
        ),
    ]
